# Generated by Django 5.2.11 on 2026-02-19 00:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("agents", "0003_real_telemetry_incidents"),
    ]

    operations = [
        migrations.CreateModel(
            name="DetectedApp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kind", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=120)),
                ("pid", models.IntegerField(blank=True, null=True)),
                ("ports_json", models.JSONField(blank=True, default=list)),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                ("first_seen", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_seen", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.RenameIndex(
            model_name="logentry",
            new_name="agents_loge_organiz_9da6d8_idx",
            old_name="agents_logen_organiz_a4d664_idx",
        ),
        migrations.RenameIndex(
            model_name="metricpoint",
            new_name="agents_metr_organiz_7fb041_idx",
            old_name="agents_metri_organiz_5f6fc1_idx",
        ),
        migrations.RenameIndex(
            model_name="processsample",
            new_name="agents_proc_organiz_d1c065_idx",
            old_name="agents_proce_organiz_a4784a_idx",
        ),
        migrations.AlterField(
            model_name="incident",
            name="type",
            field=models.CharField(
                choices=[
                    ("CPU_SPIKE", "CPU > 90% (3 samples)"),
                    ("DISK_CRITICAL", "Disk root > 90%"),
                    ("LOG_ERROR_FLOOD", "Error logs flood"),
                    ("AGENT_OFFLINE", "Agent heartbeat missing"),
                    ("HTTP_5XX_SPIKE", "HTTP 5xx spike"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="detectedapp",
            name="agent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detected_apps",
                to="agents.agent",
            ),
        ),
        migrations.AddField(
            model_name="detectedapp",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detected_apps",
                to="accounts.organization",
            ),
        ),
        migrations.AddIndex(
            model_name="detectedapp",
            index=models.Index(
                fields=["organization", "agent", "kind", "last_seen"],
                name="agents_dete_organiz_463edd_idx",
            ),
        ),
    ]
