# Generated by Django 5.2.11 on 2026-02-19 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0004_detectedapp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="cloud_metadata_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="agent",
            name="environment",
            field=models.CharField(
                choices=[("DEV", "Dev"), ("STAGE", "Stage"), ("PROD", "Prod")],
                default="PROD",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="health_score",
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name="agent",
            name="provider",
            field=models.CharField(
                choices=[
                    ("AWS", "AWS"),
                    ("AZURE", "Azure"),
                    ("GCP", "GCP"),
                    ("RAILWAY", "Railway"),
                    ("ON_PREM", "On-Prem"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="region",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="agent",
            name="tags_json",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="detectedapp",
            name="app_health_score",
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name="detectedapp",
            name="framework",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="detectedapp",
            name="process_hints_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="detectedapp",
            name="runtime",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="detectedapp",
            name="server",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name="AppServiceMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_name", models.CharField(max_length=64)),
                ("service_kind", models.CharField(max_length=64)),
                ("port", models.PositiveIntegerField(blank=True, null=True)),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_maps",
                        to="agents.detectedapp",
                    ),
                ),
            ],
            options={
                "ordering": ("service_name",),
            },
        ),
    ]
