# Generated by Django 5.2.11 on 2026-02-19 05:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("agents", "0005_agent_cloud_metadata_json_agent_environment_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HashReputationCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sha256", models.CharField(max_length=64, unique=True)),
                ("vt_json", models.JSONField(blank=True, default=dict)),
                (
                    "last_checked",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "ordering": ("-last_checked",),
            },
        ),
        migrations.CreateModel(
            name="AgentCommand",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "command_type",
                    models.CharField(
                        choices=[
                            ("START_NOCTURNAL_SCAN", "Start nocturnal scan"),
                            ("STOP_NOCTURNAL_SCAN", "Stop nocturnal scan"),
                            ("SET_NOCTURNAL_CONFIG", "Set nocturnal config"),
                        ],
                        max_length=64,
                    ),
                ),
                ("payload_json", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT", "Sent"),
                            ("ACKED", "Acked"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("CANCELED", "Canceled"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commands",
                        to="agents.agent",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_commands",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["organization", "agent", "status", "created_at"],
                        name="agents_agen_organiz_1e4f04_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="NocturnalScanRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("STOPPED", "Stopped"),
                        ],
                        default="RUNNING",
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("stats_json", models.JSONField(blank=True, default=dict)),
                ("last_progress", models.PositiveSmallIntegerField(default=0)),
                ("last_message", models.CharField(blank=True, max_length=255)),
                ("config_snapshot_json", models.JSONField(blank=True, default=dict)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nocturnal_runs",
                        to="agents.agent",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nocturnal_runs",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("-started_at",),
                "indexes": [
                    models.Index(
                        fields=["organization", "agent", "status", "started_at"],
                        name="agents_noct_organiz_e74e64_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SecurityFinding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fingerprint", models.CharField(max_length=64)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MED", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MED",
                        max_length=16,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("YARA_MATCH", "YARA match"),
                            ("VT_HASH_MATCH", "VirusTotal hash match"),
                            ("SUSPICIOUS_FILE", "Suspicious file"),
                        ],
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("details_json", models.JSONField(blank=True, default=dict)),
                ("evidence_json", models.JSONField(blank=True, default=dict)),
                ("first_seen", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_seen", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("ACK", "Ack"),
                            ("RESOLVED", "Resolved"),
                        ],
                        default="OPEN",
                        max_length=16,
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_findings",
                        to="agents.agent",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_findings",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("-last_seen",),
                "indexes": [
                    models.Index(
                        fields=[
                            "organization",
                            "agent",
                            "severity",
                            "status",
                            "last_seen",
                        ],
                        name="agents_secu_organiz_2b23c6_idx",
                    )
                ],
                "unique_together": {("organization", "agent", "fingerprint")},
            },
        ),
    ]
