# Generated by Django 5.2.11 on 2026-02-20 04:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("agents", "0006_hashreputationcache_agentcommand_nocturnalscanrun_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hashreputationcache",
            options={},
        ),
        migrations.AddField(
            model_name="agentcommand",
            name="error_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="agentcommand",
            name="finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agentcommand",
            name="result_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="agentcommand",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="agentcommand",
            name="command_type",
            field=models.CharField(
                choices=[
                    ("NIGHT_SCAN", "Night scan"),
                    ("QUARANTINE_FILE", "Quarantine file"),
                    ("KILL_PROCESS", "Kill process"),
                    ("UPDATE_CONFIG", "Update config"),
                    ("START_NOCTURNAL_SCAN", "Start nocturnal scan"),
                    ("STOP_NOCTURNAL_SCAN", "Stop nocturnal scan"),
                    ("SET_NOCTURNAL_CONFIG", "Set nocturnal config"),
                ],
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="agentcommand",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("RUNNING", "Running"),
                    ("DONE", "Done"),
                    ("FAILED", "Failed"),
                    ("SENT", "Sent"),
                    ("ACKED", "Acked"),
                    ("COMPLETED", "Completed"),
                    ("CANCELED", "Canceled"),
                ],
                default="PENDING",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="type",
            field=models.CharField(
                choices=[
                    ("CPU_SPIKE", "CPU > 90% (3 samples)"),
                    ("DISK_CRITICAL", "Disk root > 90%"),
                    ("LOG_ERROR_FLOOD", "Error logs flood"),
                    ("AGENT_OFFLINE", "Agent heartbeat missing"),
                    ("HTTP_5XX_SPIKE", "HTTP 5xx spike"),
                    ("MALWARE_SUSPECT", "Malware suspect (YARA/VT)"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="AgentConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scan_paths", models.JSONField(blank=True, default=list)),
                ("exclusions", models.JSONField(blank=True, default=list)),
                ("max_files", models.PositiveIntegerField(default=2000)),
                ("max_file_mb", models.PositiveIntegerField(default=30)),
                ("yara_ruleset_url", models.URLField(blank=True)),
                ("yara_rules_inline", models.TextField(blank=True)),
                ("vt_enabled", models.BooleanField(default=False)),
                ("vt_api_key_masked", models.CharField(blank=True, max_length=255)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config",
                        to="agents.agent",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_configs",
                        to="accounts.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ThreatFinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MED", "Medium"),
                            ("HIGH", "High"),
                            ("CRIT", "Critical"),
                        ],
                        default="MED",
                        max_length=8,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("ACK", "Ack"),
                            ("RESOLVED", "Resolved"),
                        ],
                        default="OPEN",
                        max_length=16,
                    ),
                ),
                ("file_path", models.TextField()),
                (
                    "file_hash_sha256",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("yara_rule", models.TextField(blank=True)),
                ("yara_tags", models.JSONField(blank=True, default=list)),
                ("vt_score", models.IntegerField(blank=True, null=True)),
                ("vt_permalink", models.TextField(blank=True, null=True)),
                (
                    "action_taken",
                    models.CharField(
                        choices=[
                            ("NONE", "None"),
                            ("QUARANTINED", "Quarantined"),
                            ("KILLED", "Killed"),
                            ("IGNORED", "Ignored"),
                        ],
                        default="NONE",
                        max_length=16,
                    ),
                ),
                ("quarantine_path", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="threat_findings",
                        to="agents.agent",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="threat_findings",
                        to="accounts.organization",
                    ),
                ),
                (
                    "server",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="threat_findings",
                        to="agents.detectedapp",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=[
                            "organization",
                            "agent",
                            "severity",
                            "status",
                            "created_at",
                        ],
                        name="agents_thre_organiz_2e63c1_idx",
                    )
                ],
            },
        ),
    ]
